import '.././globals.css'
import { Inter } from 'next/font/google'
import AdminHeader from './components/AdminHeader'
import AdminSideBar from './components/AdminSideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Admin Panel',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AdminHeader/>
        <div className='flex'>
            <div className='w-2/12'><AdminSideBar/></div>
            <div className='w-10/12 p-3'>{children}</div>
        </div>
        
        </body>
    </html>
  )
}
